replicaCount: 1

image:
  repository: ghcr.io/rui-armada/bestversion
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 3000
  nodePort: 30000

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: production
