apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestversion
  namespace: bestversion
  labels:
    app: bestversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestversion
  template:
    metadata:
      labels:
        app: bestversion
    spec:
      containers:
        - name: bestversion
          image: bestversion:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
