apiVersion: v1
kind: Service
metadata:
  name: bestversion
  namespace: bestversion
spec:
  selector:
    app: bestversion
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
